master:
  push:
    - name: lint and release
      docker:
        image: node:22
      imports:
        - https://cnb.cool/ycoj-ui/ycoj-secrets/-/blob/main/env.yaml
      stages:
        - name: install pnpm
          script: npm install -g pnpm
        - name: install dependencies
          script: pnpm install --frozen-lockfile
        - name: type check
          script: pnpm lint:type
        - name: lint
          script: pnpm lint
        - name: release
          script: |
            echo "SSH_HOST=$SSH_HOST" > ./scripts/.env.local
            echo "SSH_PORT=$SSH_PORT" >> ./scripts/.env.local
            echo "SSH_USER=$SSH_USER" >> ./scripts/.env.local
            echo "SSH_PASSWORD=$SSH_PASSWORD" >> ./scripts/.env.local
            echo "FRONTEND_DIR=$FRONTEND_DIR" >> ./scripts/.env.local
            pnpm release
'**':
  push:
    - name: lint
      docker:
        image: node:22
      stages:
        - name: install pnpm
          script: npm install -g pnpm
        - name: install dependencies
          script: pnpm install --frozen-lockfile
        - name: type check
          script: pnpm lint:type
        - name: lint
          script: pnpm lint
