'**':
  push:
    - name: lint
      docker:
        image: node:22
      stages:
        - name: install pnpm
          script: npm install -g pnpm
        - name: install dependencies
          script: pnpm install --frozen-lockfile
        - name: type check
          script: pnpm lint:type
        - name: lint
          script: pnpm lint
